site_name: SCA Buildsystem Documentation
pages:
- 'Overview': 'index.md'
- 'Buildsystem Infrastructure': 'infrastructure/index.md'
- 'Using the Target System':
    - 'Mounting Development Host on Target': 'target_system/mount_on_target.md'
    - 'Connecting the ECUcore-1021 Board to Development Host': 'target_system/connect_target_hardware.md'
- 'Yocto Buildsystem':
    - 'QuickStart': 'yocto/quickstart.md'
    - 'Docker': 'yocto/docker.md'
    - 'Yocto': 'yocto/yocto.md'
    - 'Systemd': 'yocto/systemd.md'
- 'Embedded Development Environment': 'dev_env.md'
- 'Device Update Management': 'device_update.md'
- 'Continious Delivery': 'cont_delivery.md'
- 'Integration Testing': 'integration_testing.md'
- 'Reference': 'refmat/index.md'
#- 'Build':
#  - 'Build für Host': 'build_host.md'
#  - 'Build fürs Target': 'build_target.md'
# theme: 'material'
theme: 'readthedocs'
extra:
    logo: 'images/sca-logo.svg'
    palette:
        primary: 'Grey'
        accent: 'Red'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    i18n:
        prev: 'Previous'
        next: 'Next'

# Extensions
markdown_extensions:
    - codehilite(css_class=code)
    - admonition
    - toc:
        permalink: '#'
